### ISSUE TITLE
Which e-mail address should we use?

### ISSUE THREAD

**Issue by simonvanderveldt** [sensemakersamsterdam/housekeeping#1]
Currently the organization's e-mail address is hosted on @johanhenselmans domain.
It would be nice if we had a web based e-mail address (for example gmail) that we can use. What do you guys think?

We could also request an amsterdam@sensemake.rs e-mail address or create a new domain (for example iotamsterdam.nl) to add the e-mail address to.

**Comment by johanhenselmans** [comment]
Op 20 dec. 2013, om 17:39 heeft Simon van der Veldt notifications@github.com het volgende geschreven:

> Currently the organization's e-mail address is hosted on @johanhenselmans domain.
> It would be nice if we had a web based e-mail address (for example gmail) that we can use. What do you guys think?

I agree completely. 

> We could also request an amsterdam@sensemake.rs e-mail address or create a new domain (for example iotamsterdam.nl) to add the e-mail address to.
> 
> —
> Reply to this email directly or view it on GitHub.

I can register a iotamsterdam.nl within 5 minutes. Just say so.

Johan Henselmans
johan@netsense.nl
